# Generated by Django 5.2 on 2025-05-11 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
