# Generated by Django 5.2 on 2025-05-11 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='valor_numerico',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
