# Generated by Django 5.2 on 2025-04-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
