# Generated by Django 5.2 on 2025-04-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'ordering': ('-price',)},
        ),
    ]
