# Generated by Django 5.2 on 2025-04-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bids_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'ordering': ('-amount',)},
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
