# Generated by Django 5.2 on 2025-04-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bids_options_rename_price_bids_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
    ]
