# Generated by Django 5.2 on 2025-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_bids_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('-price',)},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='amount',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.CharField(max_length=100),
        ),
    ]
